name: Bruno Collection Workflow

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  run-bruno-tests:
    runs-on: self-hosted   # Make sure a runner with this label is online

    steps:
      - name: Checkout the code
        uses: actions/checkout@v4.2.2

      - name: Install Node.js and npm
        uses: actions/setup-node@v3.9.1
        with:
          node-version: '22'

      - name: Install Newman and html extra globally
        run: |
          npm install -g newman
          npm install -g newman-reporter-htmlextra

      - name: Run the Bruno collection with Newman
        run: |
          newman run 'Inwarranty-flow Collection.bruno_collection.json' \
          -e QA.bruno_environment.json \
          -r cli,htmlextra \
          --reporter-htmlextra-export ./newman/index.html

      - name: Upload Newman report
        if: always()
        uses: actions/upload-artifact@v4.6.2
        with:
          name: Newman Report
          path: newman/*.html

      - name: Create GitHub Pages branch
        if: always()
        uses: peaceiris/actions-gh-pages@v4.0.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: newman/

      - name: Send Email
        if: always()
        uses: dawidd6/action-send-mail@v6
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.GITHUB_USERNAME }}
          password: ${{ secrets.GITHUB_PASSWORD }}
          subject: INWARRANTY FLOW TEST EXECUTION
          to: gopimohan7321@gmail.com
          from: ${{ secrets.GITHUB_USERNAME }}
          body: |
            Hi, 
            Phoenix inwarranty flow has been executed and the report has been published. 
            Please find the url here: https://github.com/Gopi-Gm/Test_Inwarranty-flow-Collection
